version: '3.8'
services:
#  stats-server:
#    build: ./statserver
#    container_name: statserver-container
#    ports:
#      - "9090:9090"
#      - "5005:5005"
#    depends_on:
#      - ewm-db
#    environment:
#       - URL=jdbc:postgresql://ewm-db:5432/newsdb
#       - USER=user
#       - PASSWORD=pass
#       - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
#
#  ewm-service:
#    build: ./mainserver
#    container_name: main-container
#    ports:
#      - "8080:8080"
#      - "5006:5006"
#    depends_on:
#      - ewm-db
#      - stats-server
#    environment:
#      - EWM_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/newsdb
#      - EWM_POSTGRES_USER=user
#      - EWM_POSTGRES_PASSWORD=pass
#
#      - STATS_SERVER_URL=http://stats-server:9090
#      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
#
#  ewm-db:
#    image: postgres:14-alpine
#    container_name: main-db-container
#    ports:
#      - "6542:5432"
#    environment:
#      - POSTGRES_DB=newsdb
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=pass

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

