version: '3.8'
services:
  stats-server:
    build: ./statserver
    container_name: statserver-container
    ports:
      - "9090:9090"
      - "5005:5005"
    depends_on:
      - ewm-db
    environment:
       - URL=jdbc:postgresql://ewm-db:5432/newsdb
       - USER=user
       - PASSWORD=pass
       - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  ewm-service:
    build: ./mainserver
    container_name: main-container
    ports:
      - "8080:8080"
      - "5006:5006"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - EWM_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/newsdb
      - EWM_POSTGRES_USER=user
      - EWM_POSTGRES_PASSWORD=pass

      - STATS_SERVER_URL=http://stats-server:9090
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6542:5432"
#      - "6544:5434"
#    volumes:
#      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=newsdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
